source:
  path: ../source/ReportHistory.xlsx

symbols:
  prefixes:
    WIN: WIN
    WDO: WDO
    BIT: BIT

strategies:
  groups:
    - name: Turtle
      patterns: ["TurtleS2", "TurtlePyr_1", "TurtlePyr_2"]
    - name: FVG
      patterns: ["fvg"]
    - name: RadarWIN
      patterns: ["radarwin"]
    - name: RadarWDO
      patterns: ["radarwdo"]
    - name: Soberano
      patterns: ["soberano"]
    - name: EngulfPattern
      patterns: ["engulfpattern"]
