source:
  path: ./ReportHistory-2002705608.xlsx

symbols:
  prefixes:
    WIN: WIN
    WDO: WDO
    BIT: BIT

strategies:
  groups:
    - name: Turtle
      patterns: ["turtle", "turtlepyr"]
    - name: FVG
      patterns: ["fvg"]
    - name: RadarWIN
      patterns: ["radarwin"]
    - name: RadarWDO
      patterns: ["radarwdo"]
    - name: Soberano
      patterns: ["soberano"]
    - name: EngulfPattern
      patterns: ["engulf"]
